name: PR Build Check

on:
  pull_request:
    branches:
    - master

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Set RESEND_API_KEY environment variable
      run: echo "RESEND_API_KEY=$(echo ${{ secrets.RESEND_API_KEY }})" >> $GITHUB_ENV

    - name: Run Astro build
      run: npm run build
